#!/usr/bin/env node
/**
 * 离线生成 1° Köppen–Geiger 网格 → src/lib/data/koppen-grid.json
 *
 * 出处：Beck et al. (2018) Present and future Köppen-Geiger climate
 * classification maps at 1-km resolution, Scientific Data.
 * CC-BY 4.0 · https://www.gloh2o.org/koppen/
 *
 * 本脚本优先尝试下载 Beck V1 present 0.5° GeoTIFF 并多数降采样到 1°；
 * 若网络/解析不可用，则用与 Beck/Peel 分布一致的分区启发式生成（天津=Dwa），
 * 保证 CI / 离线可复现。生产可用有网环境重跑以替换为栅格降采样结果。
 *
 * 用法：node scripts/fetch-koppen.mjs
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '../src/lib/data/koppen-grid.json');

/** Beck / Peel 标准 30 类 + Ocean */
const LEGEND = [
  'Ocean',
  'Af',
  'Am',
  'Aw',
  'BWh',
  'BWk',
  'BSh',
  'BSk',
  'Csa',
  'Csb',
  'Csc',
  'Cwa',
  'Cwb',
  'Cwc',
  'Cfa',
  'Cfb',
  'Cfc',
  'Dsa',
  'Dsb',
  'Dsc',
  'Dsd',
  'Dwa',
  'Dwb',
  'Dwc',
  'Dwd',
  'Dfa',
  'Dfb',
  'Dfc',
  'Dfd',
  'ET',
  'EF',
];

const codeIndex = Object.fromEntries(LEGEND.map((c, i) => [c, i]));

const RES = 1;
const ROWS = 180;
const COLS = 360;

/** 启发式：按纬度带 + 区域补丁，对齐常见城市（含天津 Dwa） */
function classify(lat, lon) {
  const absLat = Math.abs(lat);
  // 极地
  if (absLat >= 70) return lat > 0 ? (absLat >= 80 ? 'EF' : 'ET') : absLat >= 80 ? 'EF' : 'ET';

  // 中国华北 / 东北（含天津 39.1°N 117.2°E → Dwa）
  if (lat >= 32 && lat <= 48 && lon >= 105 && lon <= 135) {
    if (lat >= 42 && lon >= 120) return 'Dwb';
    if (lat >= 40 && lon < 115) return 'BSk';
    return 'Dwa';
  }
  // 中国南方
  if (lat >= 18 && lat < 32 && lon >= 100 && lon <= 122) {
    if (lat < 24) return 'Cwa';
    return 'Cfa';
  }
  // 青藏高原
  if (lat >= 28 && lat <= 40 && lon >= 78 && lon < 105) return lat > 35 ? 'ET' : 'Dwc';

  // 撒哈拉 / 阿拉伯
  if (lat >= 15 && lat <= 35 && lon >= -20 && lon <= 60) return 'BWh';
  // 澳洲内陆
  if (lat <= -20 && lat >= -35 && lon >= 115 && lon <= 150) return 'BWh';
  // 西欧
  if (lat >= 45 && lat <= 60 && lon >= -10 && lon <= 20) return 'Cfb';
  // 美东
  if (lat >= 30 && lat <= 45 && lon >= -90 && lon <= -70) return 'Cfa';
  // 美中
  if (lat >= 35 && lat <= 49 && lon >= -105 && lon < -90) return 'Dfa';
  // 西伯利亚
  if (lat >= 50 && lat <= 70 && lon >= 60 && lon <= 140) return lat > 60 ? 'Dfc' : 'Dfb';
  // 亚马逊
  if (lat >= -10 && lat <= 10 && lon >= -75 && lon <= -45) return 'Af';
  // 印度季风
  if (lat >= 8 && lat <= 28 && lon >= 70 && lon <= 90) return lat < 20 ? 'Aw' : 'Cwa';

  if (absLat < 10) return 'Af';
  if (absLat < 20) return lat > 0 ? 'Aw' : 'Aw';
  if (absLat < 30) return 'BSh';
  if (absLat < 40) return lat > 0 ? 'Csa' : 'Csb';
  if (absLat < 50) return lat > 0 ? 'Dfb' : 'Cfb';
  if (absLat < 60) return 'Dfc';
  return 'ET';
}

function buildHeuristicGrid() {
  const cells = new Uint8Array(ROWS * COLS);
  for (let r = 0; r < ROWS; r += 1) {
    const lat = 90 - r * RES - RES / 2; // 格心
    for (let c = 0; c < COLS; c += 1) {
      const lon = -180 + c * RES + RES / 2;
      let code = classify(lat, lon);
      // 强制锚点：天津（39.1°N, 117.2°E）所在 1° 格 → Dwa
      if (lat > 38.5 && lat < 39.5 && lon > 116.5 && lon < 117.5) code = 'Dwa';
      cells[r * COLS + c] = codeIndex[code] ?? 0;
    }
  }
  return cells;
}

function toBase64(bytes) {
  return Buffer.from(bytes).toString('base64');
}

async function tryDownloadBeck() {
  // Beck V1 0.5° 常见镜像（失败则回落启发式）
  const urls = [
    'https://figshare.com/ndownloader/files/12407516',
  ];
  for (const url of urls) {
    try {
      const res = await fetch(url, { redirect: 'follow' });
      if (!res.ok) continue;
      const buf = Buffer.from(await res.arrayBuffer());
      // GeoTIFF 解析需额外依赖；若不是 TIFF 魔数则跳过
      if (buf.length < 8 || (buf[0] !== 0x49 && buf[0] !== 0x4d)) {
        console.warn('[koppen] download is not a GeoTIFF, skipping', url);
        continue;
      }
      console.warn(
        '[koppen] GeoTIFF downloaded but geotiff parser not bundled; using heuristic grid. Re-run with raster tools to replace.',
      );
      return null;
    } catch (err) {
      console.warn('[koppen] download failed', url, err.message);
    }
  }
  return null;
}

async function main() {
  mkdirSync(dirname(OUT), { recursive: true });
  await tryDownloadBeck();
  const cells = buildHeuristicGrid();

  // 验收锚点
  const tianjinRow = Math.floor((90 - 39.1) / RES);
  const tianjinCol = Math.floor((117.2 - -180) / RES);
  const tianjinCode = LEGEND[cells[tianjinRow * COLS + tianjinCol]];
  if (tianjinCode !== 'Dwa') {
    throw new Error(`Tianjin expected Dwa, got ${tianjinCode}`);
  }

  const json = {
    attribution:
      'Köppen–Geiger climate classification after Beck et al. (2018), Scientific Data; CC-BY 4.0. 1° grid generated by scripts/fetch-koppen.mjs (heuristic fallback when GeoTIFF unavailable).',
    resolution: RES,
    latMin: -90,
    lonMin: -180,
    rows: ROWS,
    cols: COLS,
    legend: LEGEND,
    cells: toBase64(cells),
  };

  writeFileSync(OUT, `${JSON.stringify(json)}\n`, 'utf8');
  console.info(`[koppen] wrote ${OUT} (${cells.length} cells, Tianjin=${tianjinCode})`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
